### ISSUE TITLE
Spacetime rounding fractional timezones when parsing ISO times

### ISSUE THREAD

**Issue by davyuu** [spencermountain/spacetime#101]
![screen shot 2019-02-21 at 3 58 34 pm](https://user-images.githubusercontent.com/3384239/53202059-8834d680-35f3-11e9-98bc-3096dd99c1b6.png)

In my project, I am given a iso timestamp and in this case, it is a timestamp with a fractional timezone (`+5:30`). As you can see in the screenshot, I am creating an instance with the ISO timestamp in `+5:30` timezone and outputting it in `iso` format and it is returning in `+5:00` with the time unchanged.

If there are another workarounds that can get this to work, I am also happy to try them. Please let me know.

**Comment by hunteva** [comment]
looks like a bug, here is the [PR](https://github.com/spencermountain/spacetime/pull/102) to fix it.

**Comment by davyuu** [comment]
thank you @hunteva !

**Comment by davyuu** [comment]
@spencermountain Is there any timeline on when a new version with the fix will be available? That would be much appreciated. Thanks!

**Comment by spencermountain** [comment]
yeah, i tried quickly to fix those tests, then got distracted. will do it this weekend, for 5.3.0.
Thanks!

**Comment by spencermountain** [comment]
published `5.3.0`. Thanks for the help!
