### ISSUE TITLE
isDST() issues near DST change

### ISSUE THREAD

**Issue by GerryOnGithub** [spencermountain/spacetime#106]
`var s = spacetime('March 10, 2019 03:00:00', 'Canada/Pacific');
        console.log(s.isDST());`

prints false but it should print true

Try this one, bizarre output: 

`        console.log(spacetime('March 10, 2019 23:01:00', 'Canada/Pacific').isDST());
        console.log(spacetime('March 11, 2019 00:01:00', 'Canada/Pacific').isDST());
        console.log(spacetime('March 11, 2019 01:01:00', 'Canada/Pacific').isDST());
        console.log(spacetime('March 11, 2019 02:01:00', 'Canada/Pacific').isDST());
        console.log(spacetime('March 11, 2019 03:01:00', 'Canada/Pacific').isDST());`

**Comment by spencermountain** [comment]
whoa! good find. that sure looks like a bug.
i'll take a look over the next few days.
thanks

**Comment by GerryOnGithub** [comment]
I think moment.js also has a problem, might be some sort of underlying libary

**Comment by spencermountain** [comment]
oh hey, I haven't fixed this, but I've identified it as a previously-known [issue](https://github.com/spencermountain/spacetime/blob/50baf455fa648424752384a6b32e6320c47f587e/src/timezone/summerTime.js#L15):
![image](https://user-images.githubusercontent.com/399657/53570582-d9cdeb80-3b34-11e9-8299-2b76aaaae933.png)
we're using the Date object for most of the math, but when it gets *really* (+-1hr) close to the dst-change, there's a chance that the js date and the spacetime object are talking in different terms

yikes.
yeah, i'll try to fix this, or maybe at it to the docs somehow.
thanks for finding this.

**Comment by jakolion** [comment]
I also detected the error with DST for the timezone "Europe/Berlin". Since this night it says DST true and already adds 2 hours to UTC but thats wrong. DST will be enabled next weekend and currently it is still UTC +1.

**Comment by spencermountain** [comment]
gonna merge this into #182 
would love to solve this one.
