### ISSUE TITLE
CET to CEST switch fires two weeks early

### ISSUE THREAD

**Issue by valentinradu** [spencermountain/spacetime#111]
On 25 March 2019 the time offset for the CET timezone should be `+01:00` not `+02:00`. US timezones switch in the second week of March and the European ones in the last Sunday of March. There are a couple of weeks between in which this bug reproduces.

**Comment by spencermountain** [comment]
whoa!
crap. sorry about that.
I have CET mapped to `Europe/Berlin`, and I get the correct result with doing this:
`zdump -v /usr/share/zoneinfo/europe/berlin | grep 2019`
there must be a bug in the zonefile build script. I will check it out tonight.
thanks for the heads up.

**Comment by wirtaw** [comment]
Same problem +1h with all time zones. [Demo](https://jsfiddle.net/wirtaw/rgd687fz/)

**Comment by spencermountain** [comment]
yeah, we were still on 2018 dst dates:

![image](https://user-images.githubusercontent.com/399657/55078347-57bbde80-5070-11e9-91dc-a52831cc7c0d.png)
(i had simply hard-coded a 2018 in the script 😳)

fixed in 5.5.0 - please check it out

thank you for the help

**Comment by valentinradu** [comment]
@spencermountain Thanks for the quick fix! 👌🏽

**Comment by wirtaw** [comment]
@spencermountain Now works as expected, thanks!
