### ISSUE TITLE
Why is `UTC` timezone ignored when returned by `Intl.DateTimeFormat().resolvedOptions().timeZone`?

### ISSUE THREAD

**Issue by valentinradu** [spencermountain/spacetime#115]
Hi again,

I'm referring to this line of code:

https://github.com/spencermountain/spacetime/blob/master/src/timezone/guessTz.js#L17

My experience is limited with timezones standards, but I can't seem to find the logic in this statement. The bottom line is tho, when our servers return `UTC` as a timezone, it gets ignored and the default `asia/shanghai` (strange default btw, any reason for which UTC isn't the actual default, since +00:00) is returned which yields unexpected results.

**Comment by spencermountain** [comment]
yes! i think that fallback choice was changed in a pr.

I believe you're right that this behavior should change, good find.
I think that's probably a legacy check. if `Intl` returns UTC, we should map it to our UTC!

will schedule this into the next release.
thanks

**Comment by spencermountain** [comment]
fixed in `5.6.0`
thanks!
