### ISSUE TITLE
Export internal type definitions

### ISSUE THREAD

**Issue by vic08** [spencermountain/spacetime#138]
Is it ok to export internal typescript type definitions? It's going to help typescript users with defining their interfaces

**Comment by spencermountain** [comment]
ya! that's a good idea.
maybe it's as simple as adding `'types'` to the `"files"` field in the package.json
then importing them would be `require('spacetime/types')`?

**Comment by jecraig** [comment]
@vic08 Is this PR what you were thinking?

**Comment by vic08** [comment]
@jecraig yup exactly 👍  thank you very much! can't wait to be released :)

**Comment by spencermountain** [comment]
thank you!
published as `5.8.3`
