### ISSUE TITLE
spacetime cannot get 5.75 UTC Kathmandu

### ISSUE THREAD

**Issue by vchrpng** [spencermountain/spacetime#141]
Time zone named is not found in 5.75h, It actually as Kathmandu time zone

**Comment by spencermountain** [comment]
hey Joe, are you talking about `asia/kathmandu`?
5.75 [seems](https://www.timeanddate.com/time/zone/nepal/kathmandu) to be the correct offset, what are you suggesting? Happy to make any changes.
cheers
