### ISSUE TITLE
published size metrics?

### ISSUE THREAD

**Issue by fantapop** [spencermountain/spacetime#143]
I found the mention of 50KB regarding the size but its unclear if that's gzipped or not.  It would be nice to have this since one of the big value props of spacetime is its size compared to moment. See example here for timezone-support: https://github.com/prantlf/timezone-support

**Comment by spencermountain** [comment]
hey @fantapop yeah, 
you're right that it's a bit ambiguous
i'd prefer maybe just to include a link to something like this:
https://bundlephobia.com/result?p=spacetime@5.9.0
since it's always changing.

**Comment by fantapop** [comment]
Works for me. Thanks.

**Comment by spencermountain** [comment]
linked to bundlephobia on readme
thanks
