### ISSUE TITLE
typescript: import spacetime from ('spacetime') says undefined

### ISSUE THREAD

**Issue by codeHatcher** [spencermountain/spacetime#144]
I'm relatively new to typescript by my other dependencies are working ok. I have the following error when using this module import method

![image](https://user-images.githubusercontent.com/5360982/58928386-295d1e00-8707-11e9-95ae-2353c209df2b.png)

but no error when using this method
![image](https://user-images.githubusercontent.com/5360982/58928413-3e39b180-8707-11e9-9a87-029751cf7431.png)

my tslinter is complaining about the 2nd one but other than that it is working. something you may want to look into, not sure if it's specific to me

**Comment by jecraig** [comment]
@codeHatcher Can you paste in your tsconfig

**Comment by codeHatcher** [comment]
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "declaration": true,
    "outDir": "./dist",
    "strict": true,
    "sourceMap": true
  }
}
```

**Comment by jecraig** [comment]
Ok, so I think this is just an issue with the way your typescript is configured. You've got commonjs which uses

const x = require('y')

which overrides with the es6 import syntax

import x from 'y'

So either remove the module option from your tsconfig or just continue using the commonjs require syntax.

I don't think there's any issues with spacetime though.

**Comment by codeHatcher** [comment]
I appreciate you troubleshooting this with me @jecraig, I changed the tsconfig as you suggested and now get a slightly different error

I tried one where I switched to the following tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es6",
    "module": "es6",
    "declaration": true,
    "outDir": "./dist",
    "strict": true,
    "sourceMap": true
  }
}
```
and get the following error
![image](https://user-images.githubusercontent.com/5360982/59205962-f20cc800-8b71-11e9-9207-768a04923861.png)

**Comment by codeHatcher** [comment]
As i'm looking through these test cases I see there is nothing that uses the typescript non-relative resolution via a string literal e.g. `import spacetime from 'spacetime'` but rather in the test file as `import { spacetime } from './spacetime-static'`

**Comment by codeHatcher** [comment]
what's weird is it does have `spacetime_1` when I debug and that seems to be the correct function, but nothing still called `spacetime` that seems to be imported

![image](https://user-images.githubusercontent.com/5360982/59314817-07bee200-8c85-11e9-9c2b-a13e8ce01209.png)

which is when I run the debugger with the following code

![image](https://user-images.githubusercontent.com/5360982/59314825-13120d80-8c85-11e9-8ad8-58287424cb78.png)

**Comment by jecraig** [comment]
I scratched up a quick project and there do appear to be some issues using the typings without a bundler. I've been using Spacetime with Webpack no problem. I'll try looking into some solutions for using it without a bundler.

**Comment by spencermountain** [comment]
version `5.1.0` ships a `.mjs` build, that is linked in package.json.
so this *should* be working now. lemme know if there's still any weird issues.
thanks
