### ISSUE TITLE
optimize `.week()` performance

### ISSUE THREAD

**Issue by secretuser** [spencermountain/spacetime#147]
I instantiate a large number of spacetime objects and it is quite slow due to the sheer number of it.  I tried to parallelize it through webworkers, but that data cannot be memory-copied back to the main worker, making this option not useful at the moment. Is there a way to make spacetime objects work with webworkers?

**Comment by spencermountain** [comment]
hey @secretuser - you've piqued my curiosity - how many instances are you creating? What is your application, in broad terms?

i agree this limitation with webworkers is a lame one. If i were you, i'd probably flatten the date object down to an iso string with `.iso()` and ship it in/out of the workers.

the spacetime object is simply an epoch number, and an offset. Those two pieces of information should be enough to reproduce a spacetime date elsewhere.

cheers

**Comment by secretuser** [comment]
My usecase involves loading lots of data from financial markets (think futures, stocks, that kind of stuff) on different levels of granularity (minutes, hours, days, etc). (and then doing lots of analysis on said data).
Each data point / tick is associated with one or more spacetime objects, so millions of those get created. 

Love the library by the way. 

Unfortunately for me, loading those objects tend to be very slow due to sheer numbers. Currently the load is dominated by the spacetime object, so serializing that means I load them twice, making it slower than just loading them normally. going from v4 to v5 made it lots better, but still very painful due to huge number of objects.
By the way, I have the impression the week() function is lots slower compared to all other functions in the spacetime object. So I stopped using week().

**Comment by spencermountain** [comment]
whoa! that's awesome.
Yes, i can see this becoming too slow. You may want to take a look at the `Intl` browser object, which has some more low-level C-based date operations.

That's helpful to know `.week()` is the bottleneck. I'm happy to take a look at improving it.
cheers

**Comment by spencermountain** [comment]
hey @secretuser i've optimized .week() a bit. depending where in the year it is, it should is sometimes twice-as-fast now.
let me know if you see another performance outlier.
cheers

**Comment by secretuser** [comment]
wow thanks for the effort! I really appreciate it.
That speedup over large numbers should be quite noticeable. I'll the grab
the new version and check it out.

**Comment by electic** [comment]
Running into the same issue with financial data btw. We processes large amount of ticks and parsing dates becomes slow using spacetime. What is the best practice for optimizing parsing with spacetime?

**Comment by spencermountain** [comment]
Hey Raj, happy to help. Let me know how you're using the library. Weeks are particularly complicated, for a few reasons. Depending on your use case, there are a number of things you could try - You may want to try determining week segments with spacetime and then just dropping milliseconds into date-fs or the js date object.
Cheers
