### ISSUE TITLE
Is it possible to respond to invalid timezone input?

### ISSUE THREAD

**Issue by nathanburgess** [spencermountain/spacetime#150]
```js
import SpaceTime from 'spacetime'

let spacetime = new SpaceTime(new Date(), 'invalid-timezone')
```

This code will print with `console.warn`, but it doesn't throw an error. Since it also corrects the timezone, I can't figure out a way to actually detect when an invalid timezone has been specified.

**Comment by spencermountain** [comment]
ah, you're right. That's a good idea.
it should probably return a date that's invalid, shouldn't it.

I'll add this behaviour to v6. this will be a breaking change

**Comment by spencermountain** [comment]
hey Nathan, unrecognized timezones now throw an error in 6.0.0
thanks for your suggestion
cheers

**Comment by 0500843859Y** [comment]
> ```js
> ```js
> import SpaceTime from 'spacetime'
> 
> let spacetime = new SpaceTime(new Date(), 'invalid-timezone')
> ```
> 
> 
> This code will print with console.warn, but it doesn't throw an error. Since it also corrects the timezone, I can't figure out a way to actually detect when an invalid timezone has been specified.
> ```

**Comment by spencermountain** [comment]
hey @0500843859Y here's an example of the thrown error:
https://runkit.com/spencermountain/5dfa5939e7c3d5001981b592
