### ISSUE TITLE
iso-utc format without ms part

### ISSUE THREAD

**Issue by vshy108** [spencermountain/spacetime#151]
May I know if I can directly have result of 

> 2019-07-12T03:38:44Z

instead of 

> 2019-07-12T03:38:44.012Z

without splitting the result of .format('iso-utc') with dot?

thanks

**Comment by spencermountain** [comment]
hi @vshy108 good question. This should help. 
```js
spacetime.now().format('{year}-{iso-month}-{date}T{hour}:{minute}:{second}{offset}')
```
I haven't tested it, but I just copied that from the `.format('iso')` method, so it should work ok.
https://runkit.com/spencermountain/5d2894f870075d001a8be0c6
cheers
