### ISSUE TITLE
Zeropad for `hour-24` and `hour` format.

### ISSUE THREAD

**Issue by jayasurian123** [spencermountain/spacetime#154]
Is it possible to have padded hours in the format function? 

eg: 
Right now there is no way we could specify hours also need formatting. 
```
date.format('{hour-24}:{minute-pad}') // 5:05
```

Could we add a format where we could specify we need a zero padded hour also
```
date.format('{hour-24-pad}:{minute-pad}') // 05:05
```

**Comment by spencermountain** [comment]
hey, i like this idea.
will add it to the next release
cheers

**Comment by spencermountain** [comment]
added `hour-pad` and `hour-24-pad`.

`v5.10.0`
thanks
