### ISSUE TITLE
arrow function 

### ISSUE THREAD

**Issue by jfnault-seedbox** [spencermountain/spacetime#156]
I noticed that arrow function are now in your production minified build,
they weren't in the previous version 5.9.1

Since most webpack babel-loaded exclude node_modules, applications will end up having arrow functions in the build and older browser will be affected.

the solution for us was to stick a 5.9.1 but I wonder if it's in the plan for you to fix it.

Thank you

**Comment by spencermountain** [comment]
yikes! thank you for letting me know.
I will fix this asap.

**Comment by spencermountain** [comment]
fixed on 6.0.0!
thanks for the heads-up.
