### ISSUE TITLE
Type error when using the yesterday method

### ISSUE THREAD

**Issue by tenshiemi** [spencermountain/spacetime#159]
When using the yesterday method on a spacetime object I'm getting the following TS error:

`spacetime(Date.now()).yesterday();`

```Property 'yesterday' does not exist on type 'Spacetime'.ts(2339)```

**Comment by jecraig** [comment]
yesterday, now, and tomorrow are part of the spacetime constuctor object. They are not available on a constructed spacetime object.

spacetime.yesterday()

is what you would want.

**Comment by tenshiemi** [comment]
Thanks!
