### ISSUE TITLE
Invalid typing for spacetime constructor

### ISSUE THREAD

**Issue by pserrer** [spencermountain/spacetime#162]
Calling the constructor with `null` (`spacetime(null)`) isn't allowed currently.

This could be avoided by using `spacetime(null as any)` - but that doesn't seems like a good solution.

**Comment by spencermountain** [comment]
hi @pserrer thanks. Yeah, I really don't know the ins-and-outs of typescript. I bet you can tell.
`spacetime({empty || null || undefined})` should all return the same result (the current time).
What would you recommend? Thanks

**Comment by jecraig** [comment]
@pserrer I just tested this on  6.0.1 and it works fine. What version are you on? Are you sure you're tsconfig allows nulls?

![image](https://user-images.githubusercontent.com/20190406/64357897-bb085000-cfc2-11e9-9ce7-17bc02f0daa9.png)
![image](https://user-images.githubusercontent.com/20190406/64357993-e0955980-cfc2-11e9-96ee-72c23439276f.png)
