### ISSUE TITLE
Documentation can be a bit confusing around immutability

### ISSUE THREAD

**Issue by chrisirhc** [spencermountain/spacetime#163]
Hi there, this library looks really promising.
I wanted to point out that I was a bit confused as I was reading through the documentation as I saw code snippets like:

```js
<script>
  // make a new Date in New York
  var d = spacetime('March 1 2012', 'America/New_York')
  d.time('4:20pm')
  d.goto('America/Los_Angeles')
  d.time()
  //'1:20pm'
</script>
```

That snippet wouldn't work due to immutability, and instead it should be:

```js
<script>
  // make a new Date in New York
  var d = spacetime('March 1 2012', 'America/New_York')
  d = d.time('4:20pm')
  d = d.goto('America/Los_Angeles')
  console.log(d.time());
  //'1:20pm'
</script>
```

I understand the extra `d =` can impact readability but it seems like something that needs to be explicit in these code snippets since the `script` tags indicate they're ready to run if you copy-paste it into console / code pen.

I wanted to start this issue to see what others thought of this.

**Comment by spencermountain** [comment]
ah, thanks Chris. I've overlooked updating the website, haven't i.
I'll do that pronto.
thanks!

**Comment by spencermountain** [comment]
hey Chris, just fixed it up.
Thanks for the heads-up.

**Comment by chrisirhc** [comment]
Thank you!
