### ISSUE TITLE
Sao Paulo incorrect timezone conversion.

### ISSUE THREAD

**Issue by Chrischuck** [spencermountain/spacetime#169]
Hi again, and thank you so much for the quick fix last time!

This time I have another weird issue where if I convert a gmt-3 timezone to Sao Paulo time it converts it to gmt-2.

When I convert from America/Los_Angeles to Sao Paulo it works fine however. 

Here's a sample piece of code that shows the issue w/ moment-tz for comparison:

```
const spacetime = require('spacetime')
const moment = require('moment-timezone')

const t = spacetime('2019-11-05T11:00:00.000-03:00')
const t2 = moment.tz('2019-11-05T11:00:00.000-03:00', 'America/Sao_Paulo')

console.log(t.format('iso')) // 2019-11-05T11:00:00.000-03:00
console.log(t.goto('America/Sao_Paulo').format('iso')) // 2019-11-05T12:00:00.000-02:00
console.log(t2.format()) // 2019-11-05T11:00:00-03:00
```

Thanks again for your help!
-Chris

**Comment by spencermountain** [comment]
thanks chris, yeah it looks like the reckoning of sao paolo's dst is off.


```js
let t = spacetime('2019-11-05T11:00:00.000-03:00')
console.log(t.timezone().current.offset) // -3
t = t.goto('America/Sao_Paulo')
console.log(t.timezone().current.offset) // -2
console.log(t.format('iso'))
```
will take a look next week
cheers

**Comment by spencermountain** [comment]
ah, it was related to this - [Brazil Won't Change Clocks in 2019](https://www.timeanddate.com/news/time/brazil-scraps-dst.html).

removed dst for `brazil/east` and `america/sao_paulo`
will release as `6.3.0` later today
good eye!
cheers
