### ISSUE TITLE
Make spacetime.mjs ES5 compatible

### ISSUE THREAD

**Issue by tcjcodes** [spencermountain/spacetime#175]
I'm working on a project that's using spacetime (great alternative to date-fns-timezone, btw!) but unfortunately webpack is automatically pulling in spacetime.mjs when using new ES modules, which is not ES5 compatible:

`import spacetime from 'spacetime';`

In our case, this causes an "invalid syntax" exception in IE. 
Any way **spacetime.mjs** could be made ES5 compatible, like spacetime.js is?

---

For anyone else running into this, this was my workaround:
```javascript

// webpack config
resolve: {
  alias: {
     // Unfortunately, the default file for the spacetime module (spacetime.mjs)
     // is not ES5 compatible as of v6.3.0. Have webpack resolve to the ES5-compatible file instead:
    spacetime$: path.resolve(__dirname, 'node_modules/spacetime/builds/spacetime.min.js'),
  }
}
```

**Comment by spencermountain** [comment]
thanks Trina, yeah, I feel like i'm still not getting the export formats right.

My thinking was that anyone running mjs would support es6 syntax, and be using babel before putting it in the browser. That may be wrong. 

I'd be happy to change it,

for now, you can try something like `import spacetime from 'spacetime/builds/spacetime.min.js'` 
that may work.
cheers

**Comment by tcjcodes** [comment]
ES5 would be great, since it makes it universal for those using the package. In my case, I'm working on a large, shared repo at work and updating the webpack config would've been a large undertaking. It would be great for library consumers like me to not have to work around it (and _maybe_ have it automatically work in IE). Plus, it would make the format consistent with spacetime.js which is a bonus.

**Comment by spencermountain** [comment]
thanks for this. `mjs` builds now run through babel, in `v6.4.1`.
cheers
