### ISSUE TITLE
Add  Asia/Famagusta

### ISSUE THREAD

**Issue by andemerie** [spencermountain/spacetime#181]
I got this error with 'cet' and 'asia/famagusta' timezones. It appeared in Sentry.
The fact is that these timezones are taken from local settings, and aren't set manually. They occur in lines like:
```
spacetime.now()
```
These errors appeared after upgrading from 5.10.0 to 6.3.0.
Could you please support them?

**Comment by spencermountain** [comment]
thanks @andemerie - i'm happy to create `asia/famagusta`.

`'CET'` and similar should be handled with the [spacetime-informal](https://github.com/spencermountain/spacetime-informal/) plugin
cheers

**Comment by Chrischuck** [comment]
@andemerie I'm getting this issue as well on hauwei devices interestingly enough. 

Do you get an error like: 
`Error: Spacetime: Cannot find timezone named: 'cet'. Please enter an IANA timezone id.`

**Comment by spencermountain** [comment]
hey @Chrischuck that error is expected for non-iana timezones like 'cet'. You can use spacetime-informal to map them to proper iana codes.
cheers

**Comment by Chrischuck** [comment]
Thanks @spencermountain 

@andemerie  I think the best solution in this case would be to do:
```
let display = informal.display(INSERT_BROWSER_TZ)
let s = spacetime.now(display.iana)
```

For our current project, we get the timezone from IP address and roll with that throughout the application, so if that's an option for you, you might not need to use spacetime informal :)

**Comment by spencermountain** [comment]
Famagusta added in `6.4.0`
