### ISSUE TITLE
Calling .format() without a parameter does not list available formats

### ISSUE THREAD

**Issue by GavinRay97** [spencermountain/spacetime#183]
The wiki instructions on the formatting page say:

> Spacetime allows for fast rendering of dates and times in a bunch of formats. You can see all of them by calling .format() without a parameter.

https://github.com/spencermountain/spacetime/wiki/Formatting

However, calling `spacetime().format()` returns an empty string, and calling `spacetime.now().format()` yields a standard date format.

**Comment by spencermountain** [comment]
hey @GavinRay97 sorry about that. 
Looks like the documentation's old. I've fixed it to support the new syntax.
Let me know if you spot something else,
thanks
