### ISSUE TITLE
spacetime().d not returning what I would expect

### ISSUE THREAD

**Issue by jecraig** [spencermountain/spacetime#185]
new Date(spacetime(new Date()).hour(6).goto('America/Los_Angeles').hour(4).epoch)
Thu Jan 23 2020 05:01:21 GMT-0700 (Mountain Standard Time)

spacetime(new Date()).hour(6).goto('America/Los_Angeles').hour(4).d
Thu Jan 23 2020 04:01:30 GMT-0700 (Mountain Standard Time)

I thought the .d property would return the correct Date object based on the epoch in spacetime. It looks like it's returning the same time instead of the local time.

Using version 6.0.1

**Comment by spencermountain** [comment]
hey @jecraig yes, the Date object used internally is the local time, before the offset is applied.
That's part of why I didn't include it in the api originally.

Maybe we should have a `.toDate()` function, and a `.toLocalDate()`, or something, to clear this up. Any ideas?

related to #180  - it seems to be a confusing aspect of the API

**Comment by jecraig** [comment]
That would be preferable. We can mark the .d as obsolete and users can continue to use it if they want.

**Comment by jecraig** [comment]
I've held off correcting the issue in our codebase pending a proper function. 

As to which function, I'd vote for .toLocalDate().

**Comment by spencermountain** [comment]
cool. in the meantime you should be able to do:
```js
let s = spacetime()
let d = new Date(s.iso())
```
(i think)

**Comment by jecraig** [comment]
new Date(s.epoch) works as well, but I don't want to patch that in and then repatch with the proper solution.
