### ISSUE TITLE
Current builds zonefile out of date for 2020

### ISSUE THREAD

**Issue by craigpaul** [spencermountain/spacetime#194]
Hey Spencer,

Just ran into a bug formatting dates near the upcoming DST shift which is causing some grief. We've worked through it and came to the conclusion that the built zonefile for the current release doesn't include the 2020 shifts. Is it possible to get that released?

**Comment by craigpaul** [comment]
Nevermind, I didn't realize our version was out of date 👍

**Comment by spencermountain** [comment]
i'm not totally sure what the IANA update schedule is - if anyone knows, please let me know
