### ISSUE TITLE
An inclusive version of isBetween

### ISSUE THREAD

**Issue by coatesap** [spencermountain/spacetime#195]
Wanting to check whether a date falls inside an "inclusive" date range is quite common. At the moment, `isBetween()` doesn't match against the start and end dates. Having an `isBetweenInclusive()` method would be very handy.

Presumably the implementation would be:

```javascript
isBetweenInclusive: function(start, end) {
    return this.isBetween(start, end) || this.isEqual(start) || this.isEqual(end);
}
```

If that sounds sensible, I'm happy to open a PR for it.

**Comment by ElRaymond0** [comment]
I concur

**Comment by spencermountain** [comment]
hey Andy - maybe `isBetween` should just be inclusive?
i don't have strong thoughts about that either way.

**Comment by jecraig** [comment]
@spencermountain What if we just pass in an optional boolean to be inclusive. Default to false/null that way we don't break any existing code relying on it not being inclusive.

**Comment by spencermountain** [comment]
Yep I like that too. Good idea, pr welcome.

**Comment by spencermountain** [comment]
will release this as 6.5.0 over the next few days. cheers
