### ISSUE TITLE
 Bug in the spacetime hour method implementation.

### ISSUE THREAD

**Issue by svey** [spencermountain/spacetime#196]
I think this is a bug in the spacetime hour method implementation. Using either of the following returned incorrect values (the other 23 hours worked as expected):

`spacetime().hour(0)`
`spacetime().hour(1)`
same with `spacetime.now().hour(n)`

however passing an explicit date like `spacetime('2020-03-10T00:00:00Z').hour(h)` works

**Comment by spencermountain** [comment]
hey Marcus, thanks. I don't fully understand the issue, is it that `.hour(0)` goes to 12am?

just checked, this seems to work as expected
```js
 spacetime().hour(0).time() //12:30am
 spacetime().hour(1).time() //1:30am
 spacetime().hour(2).time() //1:30am
```
cheers

**Comment by spencermountain** [comment]
will reopen this if we can reproduce it,
cheers
