### ISSUE TITLE
Hard coded DST interval for timezones

### ISSUE THREAD

**Issue by parashish** [spencermountain/spacetime#203]
Hi Team,

I found an issue in this lib and this is very big issue as it has hard coded timezones. 

i.e.- For europe/london  DST interval is 31/03 to 27/10 in thi lib,
But in actual last sunday of March(29th march for this year) and last sunday of Oct is DST interval.  So this was 2 day difference between actual and library DST interval.

Is there any workaround for this as it is a very bug for where one hour difference of time can make very big impact on our all application.

**Comment by spencermountain** [comment]
hey @parashish thanks for the issue
You can see [here](https://github.com/spencermountain/spacetime/blob/master/zonefile/iana.js#L1682) that `europe/london` is set to `03/29 1am -> 10/25 2am` which matches [the official one here](https://www.timeanddate.com/time/zone/uk/london). Maybe there is a misunderstanding. Are you on `6.4.2` the latest version?
cheers

**Comment by parashish** [comment]
Thank you space time team for instant reply, please let me corect if i am
wrong for next year do i need to install latest version?

Warm regards
Ashish pareek

**Comment by spencermountain** [comment]
yes, each year we release a new build with [updated dst information](https://github.com/spencermountain/spacetime#-historical-timezone-info), just to reduce filesize. As you said, they usually change by a day or two each year.
Maybe in the future we will try to anticipate some of the changes (last sunday of October, or something). That could help with this issue you're having.
cheers
