### ISSUE TITLE
Skinny npm dist?

### ISSUE THREAD

**Issue by ryanblock** [spencermountain/spacetime#204]
Hey @spencermountain! Hope you're great.

Was wondering if you might consider a skinnier Node.js friendly dist?

These days Spacetime weighs in at just under 500KB, almost all of which is builds that aren't needed for  (our) CJS usage:

![image](https://user-images.githubusercontent.com/200964/79080054-a19d5400-7cc7-11ea-8124-838e25d3612a.png)

Thoughts on slimming the bundle size?

Thanks!

**Comment by spencermountain** [comment]
Hey, of course!
Maybe we can just kill the map file?
When it comes to building js, you guys are living in the year 3000, and all
advice is followed. I’m in bundler bankruptcy.

Hey also, is it deno-friendly? My body is ready.

My understanding:
* min - browser, unpkg
* cjs - node main, typescript
* mjs - webpack treeshakers, pika

Agree that shipping three basically identical copies is poop.
Hope you guys are safe over there.

**Comment by ryanblock** [comment]
I'd be stoked just to have the .map file killed, but idk if there's someone out there counting on that.

In theory the mjs file should be deno friendly!

Could automate an alternate npm release that kills all files except `spacetime.js` (and name it `@spacetime/core` or something).

Another option could be to do releases of each of those files, and I can npm install off the release tgz. Less nice because I don't get the benefit of patches but it'd probably be fine!

💕

**Comment by spencermountain** [comment]
removed the mapfile in `6.4.3`, the whole thing is down to 281kb now. nice find.
yeah, we chould move a lot of functionality into plugins for v7.  A lower filesize means fewer lambda fuss-ups, means better covid tracker, means sooner I can watch baseball.
thanks
