### ISSUE TITLE
Parsing a date from Iso is off by an hour

### ISSUE THREAD

**Issue by MarioLema** [spencermountain/spacetime#208]
I don't know if this is a bug or it has been reported independently or as a part or other issue tickets so forgive if it's already known behaviour.

When creating a spacetime object if using a iso date string the spacetime formating comes back one hour behind.

Javascript Date: `Fri May 15 2020 10:00:31 GMT+0100 (British Summer Time)`
Iso string: `2020-05-15T09:00:31.555Z` 
spacetime from JS: `15 May, 2020 10:00`
spacetime from iso string: `15 May, 2020 09:00`
spacetime js hour: `10`
spacetime iso hour: `9`

![Screenshot 2020-05-15 at 10 04 15](https://user-images.githubusercontent.com/35612123/82033158-3d89f900-9694-11ea-9698-a00622aab8ab.png)
![Screenshot 2020-05-15 at 10 09 42](https://user-images.githubusercontent.com/35612123/82033179-467aca80-9694-11ea-9078-7ffaa4204984.png)

**Comment by spencermountain** [comment]
hey @MarioLema this looks like the intended timezone is being lost by the various formats.
You can call `s.timezone()` on any spacetime object, to see what tz it is currently in.

We should be able to parse the proper tz from an iso-format date, but I don't think we grab the tz from `toString()` result yet.

best idea would just be to manually pass-in the timezone, as a 2nd param, when you construct the spacetime object.
cheers!
