### ISSUE TITLE
.format('month-pad') uses 0-based month, not what the doc says.

### ISSUE THREAD

**Issue by bigicoin** [spencermountain/spacetime#215]
Documentation:
```
s.format('month') // 'April'
s.format('month-short') // 'Apr'
s.format('month-pad') // '04'
```
However, as of current version `6.6.1`, `month-pad` appears to give the 0-based month value.

Here is a reproducible example directly from my node repl:
```
> const spacetime = require('spacetime');
undefined
> const s = spacetime('2017-12-27T02:44:25.292Z');
undefined
> s.format('month-pad');
'11'
> s.format('month-short');
'Dec'
```

**Comment by bigicoin** [comment]
Dug into the code and found this: https://github.com/spencermountain/spacetime/blob/master/src/methods/format/index.js#L21-L22

I guess the code is right and documentation is wrong. Should use `iso-month` instead of `month-pad` for 1-based month.

**Comment by spencermountain** [comment]
ah thank you Bigi. You're absolutely right.
I have updated the docs and added a test for this.
good eye!
