### ISSUE TITLE
How to get current time in current timezone?

### ISSUE THREAD

**Issue by erjdriver** [spencermountain/spacetime#219]
Apologies - I tried to look for a solution and couldn't find it.

How do I get the current time in the current timezone or how do I get the current timezone?

`spacetime.now()` gets the utc time - 

or if I knew the current timezone, I could do

`spacetime.now(timezone)`

Thanks.

**Comment by jecraig** [comment]
I'm not sure what you're trying to do. The spacetime library will just default to whatever your browser time is to.

![image](https://user-images.githubusercontent.com/20190406/89814463-65a4bf00-db00-11ea-93bb-10c9d8a39384.png)

**Comment by erjdriver** [comment]
I'm trying to use get the current time for the current timezone.

I'm using in the context of an app - the app is open and user changes timezones (in the phone or flies there) and I'd like to get the new local time in the local timezone...iow...i'm using a npm to create an android app and using it.

e.g. someone flies from NY to Denver.

`spacetime.now()` gets utc

The user can be in any timezone - I'd like to know that - localtime in local timezone.

**Comment by jecraig** [comment]
Make sure your timezones have the correct tz names. To see the list that spacetime supports you can use 
`spacetime.now().timezones`

And here's an example in use
![image](https://user-images.githubusercontent.com/20190406/89816397-c08be580-db03-11ea-825b-6131c59b741b.png)

**Comment by erjdriver** [comment]
When I do `spacetime.now()`, I get

`{
JS:   "epoch": 1597014104271,
JS:   "tz": "utc",
JS:   "silent": true,
JS:   "_weekStart": 1
JS: }`

Note the tz is utc - not my timezone.

That's the problem I'm trying to solve.

I'm not using this lib in a browser. I'm using it to develop an Android app using Nativescript framework. I added this lib to the project using npm.

**Comment by jecraig** [comment]
Try doing spacetime.now('america/new_york') or spacetime.now('america/denver') and see if the time that comes back with different times.

**Comment by erjdriver** [comment]
That works.

But I'm trying to get the current device/phone timezone and time.

**Comment by spencermountain** [comment]
@erjdriver yeah, if the browser doesn't support Intl, you may need to fallback to a 3rd party geolocation service 

some use [maxmind](https://www.maxmind.com/en/locate-my-ip-address), though i have no experience with it
cheers
