### ISSUE TITLE
[Typescript] Constructor won't accept ParseableDate

### ISSUE THREAD

**Issue by Nfinished** [spencermountain/spacetime#220]
When passing a value of type `ParsableDate` into the constructor it seems to get confused and disallow it, even though `ParsableDate`'s component types are all valid.

```
import spacetime, { ParsableDate } from 'spacetime'

export const isToday = (date: ParsableDate) => spacetime(date).isSame(spacetime(), 'day')
```

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type 'ParsableDate' is not assignable to parameter of type 'string'.
      Type 'number' is not assignable to type 'string'
```

Entirely possible I'm just bad at TS and this shouldn't work.

**Comment by jecraig** [comment]
Looks like you are correct. I've made a PR to address it and add the needed constructor definition.

**Comment by spencermountain** [comment]
thank you!
