### ISSUE TITLE
Typing issue with month(value)

### ISSUE THREAD

**Issue by DeLiKoO** [spencermountain/spacetime#222]
Hi,

First of all, thanks for this awesome library :)
Now, more about the issue, which occurs in TypeScript (only, I guess) :

- The month setter is defined as :
`month(value: string): Spacetime`

- Whereas the documentation states that its function is to :
`set the zero-based month-number (0-11). Also accepts 'June', or 'oct'.`

- The definition should probably be :
`month(value: string|number): Spacetime`

Passing the month number as a string argument (i.e. the string '0' instead of the number 0) causes misinterpretation by the library, which oddly seems to map '0' to december (I'm guessing it's falling into the default case).

Fixing the type definition and passing a number from TypeScript solved the issue for me.
Throwing an exception when the value argument is not parseable could also be beneficial to the library users.

**Comment by spencermountain** [comment]
this is fixed in `6.6.3`
thanks @DeLiKoO

**Comment by DeLiKoO** [comment]
Thank you Mr ! 👍
