### ISSUE TITLE
[Typescript] constructor won't accept combined type

### ISSUE THREAD

**Issue by Nfinished** [spencermountain/spacetime#225]
Hi! Coming at you with another typing issue in the constructor. No overload matches the call `string | Date` . I'm guessing this probably extends to other partial implementations of `ParsableDate` as well.

**Comment by jecraig** [comment]
I just tried that out and it was able to use the ParsableDate overload just fine. What version of Typescript are you using, I tried with 3.9.7. The Typescript team has been improving the typing system to handle these situations better.

**Comment by Nfinished** [comment]
Odd, maybe I jumped the gun and should've restarted my TS server in vscode. Definitely seems to be ok with it now. Thank you!
