### ISSUE TITLE
Creating dates with Array returns incorrect date sometimes

### ISSUE THREAD

**Issue by johnfumaster** [spencermountain/spacetime#229]
Sometimes when creating dates with spacetime and calling `d` property, it's returning the wrong date.  

Set your machine's timezone to `Australia/Sydney`
Then create a spacetime object using:
`spacetime([2020, 9, 4])`

**Expected result:**
`d` should return October 4th

**Actual result**
`d` returning October 3rd

What's strange is when you create a date with `spacetime([2020, 9, 5])`, it return you the correct date.

**Comment by spencermountain** [comment]
yeah, the d property doesn't have the offset applied, so it will be wrong some of the time.
it's pretty tricky, and I still get my head stuck on it sometimes,
but i think there's *no way* to create a javascript date of a remote timezone properly - because it's always implicitly in your local timezone.
Maybe we should deprecate `.d` or add a warning of some kind.

**Comment by spencermountain** [comment]
i understand wanting to have a javascript date object but I think the best plan is to avoid it, when possible.

it would be nice if we could make a `spacetime.toDate()` or something, but I don't think it will be valid - there is probably just too many gotchas doing that.

**Comment by jecraig** [comment]
We have spacetime.toLocalDate() already implemented to try and solve this. It returns a javascript Date that is in the same timezone as the current browser time.

<code>
	SpaceTime.prototype.toLocalDate = function () {
	  return new Date(this.epoch);
	};
</code>

**Comment by johnfumaster** [comment]
@jecraig, I tried using `toLocalDate()` too.  Didn't help.  eg. If you go to `spacetime.how` and put this in the console...
`spacetime([2020, 9, 4]).toLocalDate()`.  You'd expect it to be **October 4th 2020**.  But it returns me **October 3rd 2020** instead.  It's just that date.  Any other date works as expected.  If my computer's timezone is changed to UTC, it would work.  But I can't enforce what my users timezones are, so it's still a bug.

**Comment by johnfumaster** [comment]
@spencermountain I'm not trying to create a native date object in a remote timezone.  I've been creating and assigning spacetime objects for each day in a calendar.  I'm using the spacetime object to perform comparison operations for my date range select calendar, which doesn't need to know anything about timezones.

**Comment by spencermountain** [comment]
hey @johnfumaster yeah, it's tricky, but this is the sort of issue I was describing.
The js date object is always implicitly in timezone, and will produce these sort of off-by-one errors around a dst change.
The epoch too, is not the correct time, until your offset is applied. A spacetime date is the application of the epoch and an offset.

You may have some success outputing iso strings, and creating dates from them. iso strings involve offset values, but your mileage may vary.

Let me know if you can reproduce a spacetime bug, without converting it to a js date object.
Maybe this should be more clear in the docs!
cheers
