### ISSUE TITLE
Time zone abbreviations and aliases

### ISSUE THREAD

**Issue by spencermountain** [spencermountain/spacetime#23]
support 
[abbreviation](https://en.wikipedia.org/wiki/List_of_time_zone_abbreviations) to IANA.

`PST` -> `Canada/Pacific` etc.

may need to do it manually, i don't see it anywhere
(from #19 )

**Comment by clekili** [comment]
great lib! Any guesses when abbreviations feature would be ready? I am more than willing to help if I can!

**Comment by spencermountain** [comment]
hey can, yeah i stopped half-way through cause i got confused a little bit by something.
you can see the (some?) data [here](https://github.com/smallwins/spacetime/blob/master/data/abbreviations.js) i'm not sure if it's complete or not.

the trick, if i remember, was that `PST` and `PDT` refer to the same iana timezone, but should somehow move the date/offset. If i say `June 5th PDT` and `June 5th PST`, one of those should throw an error, i guess?

it's a good idea, and we definitely should do it. prs welcome

**Comment by spencermountain** [comment]
hey @clekili , this is supported now in `5.1.0`
let me know if you run into any issues.
cheers
