### ISSUE TITLE
Cannot find timezone named: America/Fort_Nelson

### ISSUE THREAD

**Issue by craigpaul** [spencermountain/spacetime#230]
Hey there, had an error pop up a couple of times lately stating that spacetime cannot find a timezone named `America/Fort_Nelson`. Did a quick search of the source code and it appears that it is indeed not there to be found haha. Is it possible to add that timezone to the build?

https://timezonedb.com/time-zones/America/Fort_Nelson

**Comment by spencermountain** [comment]
hey, of course -  good find.
Happy to add it in.
if you're in a pinch, you can add it to `./zonefile/iana.js` and run `npm run pack`
otherwise, i'll add this in the next release
cheers

**Comment by craigpaul** [comment]
Awesome! Thanks Spencer!

**Comment by spencermountain** [comment]
fixed in `v6.7.0`
cheers
