### ISSUE TITLE
time() should accept 12-hour times that contain a space before the am/pm suffix

### ISSUE THREAD

**Issue by coatesap** [spencermountain/spacetime#238]
Currently the `time()` setter accepts a 12-hour time in the format "6:30pm", however "6:30 pm" fails. 

```javascript
console.log(spacetime().time('6:30 pm').format('nice')) // Nov 11th, 6:30am
```

Having a space before the am/pm suffix seems fairly common, and therefore should be supported. 

Happy to create a PR for this if that is acceptable.

**Comment by spencermountain** [comment]
👏👏
