### ISSUE TITLE
Timezone 13h - New Zealand

### ISSUE THREAD

**Issue by scottholdren** [spencermountain/spacetime#242]
We are getting invalid timezone errors from New Zealand, where the timezone is being reported as '13h'.  +13 isn't valid according to

`const toIana = function(num) {
  num = Number(num)
  if (num > -13 && num < 13) {
    num = num * -1 //it's opposite!
    num = (num > 0 ? '+' : '') + num //add plus sign
    return 'etc/gmt' + num
  }
  return null
}`

If I expand the range for num, it sets the timezone to 'etc/gmt-13', but I'm not sure that's right.  NZ is currently GMT+13.

**Comment by spencermountain** [comment]
hey scott, thanks for the issue.
Just to clarify, you are entering `spacetime(null, '13h')` right?
it does get pretty tricky when date formats reverse the offset. I'm happy to add a `<= 13` if that solves your problem.
cheers

**Comment by scottholdren** [comment]
Thank you for taking a look.  13h is coming from the browser, we're not setting the tz it's just autodetecting from the browser.  I've tested out `<= 13` and it does seem to fix the error and the date/time looks correct.

**Comment by scottholdren** [comment]
Clarification - this is the relevant code we are using:

`let currentOffset = spacetime.now().timezone().current.offset.toString();`
`return spacetime(date, 'Etc/GMT').goto(currentOffset + 'h').d;`

so we are getting 13 as an offset from spacetime, but an error when we try to convert using that offset.  I believe 13h or 13 or +13 would all cause an error.

**Comment by spencermountain** [comment]
fixed in `v6.10.1`
thanks for your help. Let me know if the issue continues.
