### ISSUE TITLE
America/Dawson is now a non DST timezone.

### ISSUE THREAD

**Issue by akilansengottaiyan** [spencermountain/spacetime#243]
Good day!
In the latest update 6.10.0, no DST is present in America/Dawson timezone.
Looking in the code America/Dawson tz has been moved from `"-7|n|03/08:02->11/01:02"` to `"-7|n"` in `zonefile/_build.json`
in this PR **https://github.com/spencermountain/spacetime/pull/241/.**
If I am right, this change has removed DST for America/Dawson timezone but it shouldn't.
Since this change, America/Dawson timezone is now without dst settings but i guess it should be there.
Feel free to correct me.
Thanks.

**Comment by spencermountain** [comment]
hey Akilan, thanks for the issue. I think you're right.
I read [this](https://www.timeanddate.com/news/time/yukon-canada-permanent-dst.html) and I was trying to be clever by being early, and removed this dst change manually.
That was probably a dumb idea - out of curiosity, how did you find this was out of alignment with zoneinfo?
good catch!

**Comment by akilansengottaiyan** [comment]
Hey Spencer, thanks for the quick reply and this awesome library. I am using **react-timezone-select** which in turn uses spacetime's zoneinfo. I figured out a bug in the library related to the timezone in question and while tracing the bug it landed me here. When I could expect this to be fixed? If the fix is just reverting the change, I would like to raise a PR.

**Comment by spencermountain** [comment]
sure, I can do a release on Monday.
cheers

**Comment by spencermountain** [comment]
ok the yukon dst has been added back now, in v6.10.1
appreciate your help
cheers
