### ISSUE TITLE
i18n month/day lowercase

### ISSUE THREAD

**Issue by KaylaBrady** [spencermountain/spacetime#251]
`i18n` accepts list of month/day names for non-English languages, but these are always displayed in title case. However, that is not always the standard way to display a date - ex: in French and Spanish, day / month names may be lowercase. 
https://github.com/spencermountain/spacetime/blob/8d00921797fb0190345029264ad4ae5ffa225677/src/methods/format/index.js#L17

What is the intention of having these always title cased, and could a setting be exposed to override this behavior?

**Comment by spencermountain** [comment]
hey - good question. I really have no opinions on this.
I suppose the lowercase version is used internally, then we assumed everyone titlecases them.
Any solution to this is welcome.
cheers

**Comment by KaylaBrady** [comment]
@spencermountain Here's a possible solution! https://github.com/spencermountain/spacetime/pull/253

**Comment by spencermountain** [comment]
this is released now as `v6.12.2`
thank you!
