### ISSUE TITLE
Typescript: Constructor Options missing

### ISSUE THREAD

**Issue by Serraniel** [spencermountain/spacetime#255]
According to https://github.com/spencermountain/spacetime#ddmmyyy-interpretation an object can be passed with `dmy: true` to enabled a *DD/MM/YYYY* interpretation:
```ts
spacetime('12/01/2018', null, { dmy: true }) //jan 12th
```

However, this constructor is not allowed according to the type definitions delivered:
![image](https://user-images.githubusercontent.com/8461282/103292234-b81e4380-49ed-11eb-8f0d-635ddd65fa84.png)

**Comment by spencermountain** [comment]
released in 6.12.3
thank you!
