### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by frenchbread** [spencermountain/spacetime#262]
Hey,

Thanks for a very good library!

I've just noticed a little issue. When using `.every(...)` function to list dates **with week number**, for some reason at the end of year I get something like this: 

```
2020/12/20 51
2020/12/21 52
2020/12/22 52
2020/12/23 52
2020/12/24 52
2020/12/25 52
2020/12/26 52
2020/12/27 52
2020/12/28 52
2020/12/29 52
2020/12/30 52
2020/12/31 52
2021/01/01 1
2021/01/02 1
```

... and it does not look right since week lasts no longer than 7 days.  Have not tested it for every year, but for '21 I get this:

```
2021/12/19 51
2021/12/20 52
2021/12/21 52
2021/12/22 52
2021/12/23 52
2021/12/24 52
2021/12/25 52
2021/12/26 52
2021/12/27 52
2021/12/28 52
2021/12/29 52
2021/12/30 52
2021/12/31 52
2022/01/01 2
2022/01/02 2
```

PS. I'm using this within vue app which requires unique `keys` for each iterative component and when placing it as weeks list gives an error.

**Comment by spencermountain** [comment]
yikes!
will check it out this week.
thank you

**Comment by spencermountain** [comment]
hey @frenchbread - I reproduced this, and found a bunch of problems. Thanks for your help.

I've tweaked `.week()` to allow returning [a 53rd week](https://en.m.wikipedia.org/wiki/ISO_week_date), and released this as **6.13.0** -  But I agree it's pretty awkward, skipping right to the 2nd week:

```js
let year = 2020
let start = spacetime('dec 1 ' + year)
let end = spacetime('jan 20 ' + (year + 1))
start.every('week', end).forEach((d) => {
  console.log(d.format(), d.week())
})
/*
2020-12-07 50
2020-12-14 51
2020-12-21 52
2020-12-28 53
2021-01-04 2
2021-01-11 3
2021-01-18 4
*/
```

`.week()` calculates ISO week by which year the Thursday falls, but that is creating some unintuitive behaviour, so this may have to be considered.
will leave this open.
cheers

**Comment by frenchbread** [comment]
Hi @spencermountain,

Thanks for quick response.

I'll keep this in mind, this though fix should be enough for my issue.

**Comment by crazy-weasel** [comment]
Hi!

>But I agree it's pretty awkward, skipping right to the 2nd week:

Skipping should not be necessary because the week always starts with week 1, even if some of the first days of a year belong to the week of the last year.

> 2020-12-21 52
> 2020-12-28 53
> 2021-01-04 2
> `.week()` calculates ISO week by which year the Thursday falls, but that is creating some unintuitive behaviour, so this may have to be considered. will leave this open. cheers

So 2021-01-04 is in week 2020-W01, and 2021-01-03 is in the same week as 2020-12-31: 2020-W53.

I generated the following week numbers with spacetime and added the correct week-number in parenthesis:
```
2020-12-27: 52 (52)
2020-12-28: 53 (53)
2021-01-01:  1 (53)
2021-01-04:  2 ( 1)
2021-12-27: 53 (52)
2021-12-31: 53 (52)
2022-01-01:  2 (52)
2022-01-03:  3 ( 1)
```

Greetings :)

**Comment by spencermountain** [comment]
thank you @crazy-weasel - if there's something I can do to clear this up, please let me know.
If it's broken, it's probably because it hurts my head, just thinking about it.
cheers!
