### ISSUE TITLE
Will it work for a website for various dates?

### ISSUE THREAD

**Issue by naziko2411** [spencermountain/spacetime#266]
Hey, there! I was wondering if it works on websites for a specific dates and years.

**Comment by spencermountain** [comment]
hi @naziko2411 , you'll have to describe your question more clearly for me to help you.
cheers

**Comment by naziko2411** [comment]
For example, Google. Using it with specific dates and years.

**Comment by spencermountain** [comment]
yes.

**Comment by naziko2411** [comment]
Thank you!

**Comment by naziko2411** [comment]
I will ask more questions later.
