### ISSUE TITLE
Error running spacetime

### ISSUE THREAD

**Issue by AbhiPanseriya** [spencermountain/spacetime#277]
![image](https://user-images.githubusercontent.com/42121122/114674061-74ddab80-9d24-11eb-9cf7-c53e9e6f0ddc.png)

got this error while running my angular build.

**Comment by spencermountain** [comment]
thanks Abhi, i'm seeing this too. The rules around this must have changed recently.
happy to fix this
cheers

**Comment by spencermountain** [comment]
fixed on  6.16.0
thanks

**Comment by AbhiPanseriya** [comment]
thank you so much
