### ISSUE TITLE
Can I revisit websites for previous dates such as in 2018 or 2019?

### ISSUE THREAD

**Issue by naziko2411** [spencermountain/spacetime#282]
I have another question. I was wondering that can I revisit any websites for my curiosity?

**Comment by spencermountain** [comment]
Are you talking about viewing saved snapshots of webpages on the internet?
I would use something like https://archive.org/web/

This does not have anything to do with this software library,
Please only create issues if you find problems with this library. Thank you.

**Comment by naziko2411** [comment]
You're welcome.
