### ISSUE TITLE
Adding a day fails when interval falls over a DST change

### ISSUE THREAD

**Issue by coatesap** [spencermountain/spacetime#296]
```js
const start = spacetime('2021-10-31', 'Europe/London').startOf('day')
const end = start.add(1, 'day')

console.log(start.format('iso-utc'), end.format('iso-utc')) // "2021-10-30T23:00:00.000Z", ""
```

https://jsfiddle.net/coatesap/bk5p3avw/

**Comment by coatesap** [comment]
I've submitted a #297 to fix this now. 

This caused a nasty bug in our app, as `every()` relies on `add` working correctly, so generating date ranges over a DST change was completely screwy.

**Comment by spencermountain** [comment]
thank you for your help!
