### ISSUE TITLE
'yy' format in unixFmt doesn't pad with zeros 

### ISSUE THREAD

**Issue by tomfen** [spencermountain/spacetime#302]
https://github.com/spencermountain/spacetime/blob/ea703a7d557efd90ccae894db96368d750be93b6/src/methods/format/unixFmt.js#L14-L17

This fails if the two last digits begin with a zero (eg. 2000). Parsing to int should be removed.

**Comment by spencermountain** [comment]
hey @tomfen - thank you. this is a good find.
will add it to the next release.
cheers
