### ISSUE TITLE
The GitHub Icon on Home Page is displaced

### ISSUE THREAD

**Issue by RajMhatre20** [spencermountain/spacetime#306]
The GitHub link and icon on the home page is separated from each other
Current state:
![image](https://user-images.githubusercontent.com/68785723/138497358-3d1dc144-220d-41ea-9fbf-2f5d96656adb.png)

we can embed the link into the icon for ease of use.

Can I work on this issue?

**Comment by jecraig** [comment]
No problem. Just make a PR for it.

**Comment by sh1001** [comment]
I see the issue is not solved yet. @jecraig I think [spacetime site](https://spacetime.how/) is being hosted separately and is not included in this source code.

**Comment by spencermountain** [comment]
hey Raj, the website code is on the [gh-pages](https://github.com/spencermountain/spacetime/tree/gh-pages) branch of this repository - feel free to make any layout changes you'd like.
cheers
