### ISSUE TITLE
silent option is not working

### ISSUE THREAD

**Issue by joshball** [spencermountain/spacetime#308]
I cannot trigger an [Ambiguity Warning](https://github.com/spencermountain/spacetime/blob/master/README.md#ambiguity-warnings) by setting the `silent `option to `false`

It looks like there is some faulty logic in [constructor](https://github.com/spencermountain/spacetime/blob/ce75eaaee5316971a548e84b276a712ad58f84a5/src/spacetime.js#L14):
```
this.silent = options.silent || true
```

That is strange logic to parse as written as `options.silent` is passed in as false according to the [README](https://github.com/spencermountain/spacetime/blob/master/README.md#ambiguity-warnings):
```
let s = spacetime(123456, 'UTC', {
  silent: false
})
```
I guess a few possible fixes:
1. Assume a warning by default, and make 'silent' something you have to pass in to avoid the warning (probably the best, but might piss people off)
2. Rename the flag to warn, and set it to true to get the warn
3. Or just fix it in place:

Add a new method:
```
const isSilentSetToFalse = (opt) => typeof opt.silent === 'boolean' && opt.silent === false;
```
Then something like this:
```
this.silent = true 
if(isSilentSetToFalse(options)) {options.silent = false}
```
Or something equally as confusing:
```
this.silent = !isSilentSetToFalse(options)
```

And of course, add a test or two.

**Comment by spencermountain** [comment]
Hey Josh! Great idea. Pr welcomed!

**Comment by Mitsunee** [comment]
would a simple change to this solve the issue? 

```
this.silent = options.silent ?? true
```

That is what I use in modern-diacritics as both current node versions as well as all modern browsers now support the `??` operator (more info: [Nullish coalescing operator (??) on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator))

**Comment by spencermountain** [comment]
yep! that sounds good to me.
thanks
