### ISSUE TITLE
subtracting months issue

### ISSUE THREAD

**Issue by Roman-Vala** [spencermountain/spacetime#312]
Hi there,

I was subtracting months and got same result subtracting 25 and 13, how come ???

const firstOfThisMonth = spacetime.now().startOf('month');
const minus25Months= firstOfThisMonth.subtract(25, 'month');   
const minus13Months= firstOfThisMonth.subtract(13, 'month');   
console.log(firstOfThisMonth.iso(),minus25Months.iso(),minus13Months.iso());

2022-01-01T00:00:00.000+11:00 
2020-12-01T00:00:00.000+11:00 
2020-12-01T00:00:00.000+11:00

**Comment by spencermountain** [comment]
This is a very good issue. I will take a look tomorrow. Thanks

**Comment by spencermountain** [comment]
fixed in 7.0.0
thanks for the heads-up.

**Comment by Roman-Vala** [comment]
Thanks for the prompt fix!
