### ISSUE TITLE
Failed to compile after upgrading to 7.0.0

### ISSUE THREAD

**Issue by zestzero** [spencermountain/spacetime#314]
When execute `npm build`
![Screen Shot 2565-01-06 at 17 21 07](https://user-images.githubusercontent.com/3611918/148368131-5c37f45c-2048-4970-9e70-168fbd61f11f.png)

checked in `node_modules/spacetime` doesn't contain `_version.js`
![Screen Shot 2565-01-06 at 17 21 22](https://user-images.githubusercontent.com/3611918/148368150-0d3be10b-98b3-46f6-a21d-f761f175b00a.png)

**Comment by spencermountain** [comment]
Ahhh
Thank you. Gimme a few minutes

**Comment by spencermountain** [comment]
fixed in 7.0.1 - thanks for the heads-up
