### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by ansf** [spencermountain/spacetime#321]
The "Full API" link leads to https://observablehq.com/@spencermountain/spacetime-api which seems to be broken (just a bunch of  `RuntimeError: The string did not match the expected pattern` messages).

There is also the API section at the bottom of https://spacetime.how but this seems incomplete (specifically, I am missing the `epoch` property).

**Comment by spencermountain** [comment]
ahh - this got borked in the last release.
fixed. thank you

yeah - we should fix/document the `epoch` and `d` getters. Will add that to the next release
cheers

**Comment by ansf** [comment]
cool! thanks for the quick response 👍
