### ISSUE TITLE
Cannot find timezone named: 'Africa/Asmara'

### ISSUE THREAD

**Issue by Hectix** [spencermountain/spacetime#323]
Error in render: "Error: Spacetime: Cannot find timezone named: 'Africa/Asmara'. Please enter an IANA timezone id."

To my knowledge, this is a valid IANA timezone. Can this be fixed?

**Comment by spencermountain** [comment]
hey @Hectix - yeah, it's amazing how tricky these timezone ids are.
i believe the iana code is now `Africa/Asmera` - although we should support both.
Maybe we should add [this list of aliases](https://github.com/spencermountain/timezone-soft/blob/ddff1b4b7da0ccd738ec1e93a48f95a656397976/data/more/aliases.js) - or if there are more, please let me know.

You can see the current (and evolving) set of iana codes and aliase [here](https://github.com/spencermountain/spacetime/tree/master/zonefile) - prs welcomed
cheers

**Comment by Hectix** [comment]
#324 Merged. @spencermountain Thanks!!!
