### ISSUE TITLE
Invalid date string parsing

### ISSUE THREAD

**Issue by gk061090** [spencermountain/spacetime#330]
Hi. Seems to be a bug.
I entered the month incorrectly:
```
const testDate = spacetime('11.13.2022', 'Europe/Berlin');
testDate.isValid(); // true, but should be false
testDate.unixFmt("yyyy-MM-dd"); // "2022-11-13" - incorrect
```
I entered the day and month incorrectly:
```
const testDate = spacetime('13.13.2022', 'Europe/Berlin');
testDate.isValid(); // false - OK
testDate.unixFmt("yyyy-MM-dd"); // "1970-01-01" - OK
```

**Comment by jecraig** [comment]
I would advocate for leaving it as is. @gk061090, you can pass in whether you want dmy in the spacetime constructor. 

spacetime('12/01/2018', null, { dmy: true }) //jan 12th

**Comment by gk061090** [comment]
Thanks. I think it's enough to create an abstraction over spacetime and pass the parameter `{ dmy: true }`.
But I also have a problem with `yyyy-MM-dd` format:
```
new Date('2022-13-02') // Invalid Date - OK
spacetime("2022-13-02").isValid() // true - "2022-02-13" - incorrect
```
How can I fix it? Sorry I forgot to write this case in the first message

**Comment by jecraig** [comment]
There is no 13th month so 2022-13-02 can't be a ymd.

**Comment by gk061090** [comment]
Right, and `spacetime("2022-13-02").isValid()` should be `false` (not `true`). Also `spacetime("2022-13-02").unixFmt("yyyy-MM-dd")` returns `"2022-02-13"`
