### ISSUE TITLE
Wrong type returned for time()

### ISSUE THREAD

**Issue by lukevella** [spencermountain/spacetime#331]
Hi, I noticed there seems to be a mistake in the types for the `time()` method. Currently it returns `number` but it actually returns a `string`.

https://github.com/spencermountain/spacetime/blob/3a6d8c3ff5db68ec6956e0f3273862eb5a828c04/types/types.d.ts#L195

**Comment by spencermountain** [comment]
ahh, good catch. thank you.

**Comment by spencermountain** [comment]
fixed in 7.1.3
cheers
