### ISSUE TITLE
Default Timezone Offset wrong?

### ISSUE THREAD

**Issue by kimonneuhoff** [spencermountain/spacetime#337]
Hello,

Why is the default offset of "Europe/Berlin" 2? Germany is in UTC+1 by default and only while DST UTC+2. Or am i wrong??

-> spacetime.now().timezone()
=
{name: 'Europe/Berlin', hasDst: true, default_offset: 2, hemisphere: 'North', current: {…}, …}
change: {start: '03/27:02', back: '10/30:03'}
current: {offset: 2, isDST: true}
default_offset: 2
hasDst: true
hemisphere: "North"
name: "Europe/Berlin"
[[Prototype]]: Object

**Comment by spencermountain** [comment]
hey Kimon, yeah, the library assumes the current timezone of the computer, if none is supplied. This can be a gotcha, if your code is running on a server somewhere.

Berlin is [currently in +2](https://www.timeanddate.com/worldclock/germany/berlin) - you can see the spacetime timezone [like this](https://runkit.com/spencermountain/625884975d93970008ddebcf)
cheers
