### ISSUE TITLE
i18n method is not included on the types

### ISSUE THREAD

**Issue by ellipticaldoor** [spencermountain/spacetime#338]
When I try to use the i18n method I get the type error "Property 'i18n' does not exist on type 'Spacetime'" though it works fine. Seems like this method is missing on the types.

Also I had to find how to use this looking at the tests, I couldn't find it in the docs or in the wiki.

**Comment by spencermountain** [comment]
hey Miguel - good catch. Looks like these are missing. Will add these in the next release
cheers

**Comment by spencermountain** [comment]
i18n type added in `7.1.4`

method is documented here:
https://github.com/spencermountain/spacetime#custom-languages
thanks

**Comment by ellipticaldoor** [comment]
wow thank you!
