### ISSUE TITLE
Incorrect instance construction when using a timezone

### ISSUE THREAD

**Issue by coatesap** [spencermountain/spacetime#343]
The construction of a Spacetime instance seems to be affected by the system timezone, even when a specific timezone is supplied as the second parameter:

```js
// system timezone set to Europe/London

spacetime('2022-10-30 00:00:00', 'America/New_York').epoch
// = 1667098800000 - wrong - should be: 1667102400000

spacetime('2022-10-30 00:00:00', 'America/New_York').format('iso-utc')
// = 2022-10-30T03:00:00.000Z - wrong - should be: 2022-10-30T04:00:00.000Z
```

This seems to being affected by the fact that in London there is a DST change on that day. But that should be irrelevant given that we've been explicit about what we mean in the constructor.

**Comment by spencermountain** [comment]
hey Andy, could this be #235 ?

**Comment by coatesap** [comment]
@spencermountain - Was this fixed as part of some other issue or branch?

**Comment by spencermountain** [comment]
Nope, still exists as #235 I’m afraid. Fix in the works but it’s taking time.
