### ISSUE TITLE
DST failure

### ISSUE THREAD

**Issue by basvanmeurs** [spencermountain/spacetime#349]
`spacetime("2023-03-27 00:00", "Europe/Amsterdam").epoch - spacetime("2023-03-26 00:00", "Europe/Amsterdam").epoch`

Gives 86400000 like any non-DST day.

But DST changes at `2023-03-26 02:00` in Europe/Amsterdam timezone. So it should be 82800000

**Comment by spencermountain** [comment]
hey Bas, yep - i'll update to 2023 dst once the fall dst finishes.
I'm working on a version that is more predictive of next-year's dst, and it should be ready this fall.
sorry bout this.
cheers

**Comment by spencermountain** [comment]
DST dates updated to 2023 in 7.3.0 - let me know if you see any issues
cheers
