### ISSUE TITLE
Running "npm test" does not work in windows

### ISSUE THREAD

**Issue by chintan-golakiya** [spencermountain/spacetime#354]
while running ``` npm test ``` on windows, it doesn't work.
Here is this error:
```
$ npm test     

> spacetime@7.2.0 test
> TESTENV=dev tape ./test/**/*.test.js | tap-dancer  --color always

'TESTENV' is not recognized as an internal or external command,
operable program or batch file.
```
Removing ``` TESTENV=dev ``` from ``` package.json ``` solves issue for me.
To solve this issue for all I think one of following approach can help.
1) Remove ``` TESTENV=dev ``` from ``` package.json ``` as this does not work in all OS and setting environment variable in ``` .env ``` could be mentioned in ``` contributing.md ``` file
2) Remove ``` TESTENV=dev ``` from ``` package.json ``` as this does not work in all OS and setting environment variable using ``` process.env.TESTENV='dev'; ``` in all ``` *.test.js ``` files.

please share which could be good solution, I would like contribute in required changes for this.

**Comment by spencermountain** [comment]
added to 7.3.0
thanks
