### ISSUE TITLE
iso() method is typed to return a number?

### ISSUE THREAD

**Issue by vresetnikov** [spencermountain/spacetime#363]
Hello, 

The iso() method is typed to return a `number`:

```ts
  /** get the date/time as ISO 8601 */
  iso(): number
```

however the following:

`console.log(typeof(spacetime(date, 'UTC').startOf('day').iso()));`

will produce a `string`.

Is this intended and am I missing something?

**Comment by spencermountain** [comment]
thanks Vladimir, will fix this in the next release
cheers

**Comment by spencermountain** [comment]
fixed in 7.4.2
thank you
