### ISSUE TITLE
Month number is always -1

### ISSUE THREAD

**Issue by vresetnikov** [spencermountain/spacetime#375]
Hello, 

Considering the following tests:

```ts
const spacetime = require("spacetime");

const timestamp1 = spacetime("2022-10-01T00:00:00.000Z", "Europe/Rome");

//returns 2022-09 (September??)
const timestamp1_test1 = timestamp1.format('{year}-{month-pad}');
console.log(timestamp1_test1);

//returns 2022-09 (September??)
const timestamp1_test2 = timestamp1.format('{year}-{month-number}');
console.log(timestamp1_test2);

//returns 2022-10-01, desired outcome BUT illegal (format() method requires at least 1 argument)
const timestamp1_test3 = timestamp1.format();
console.log(timestamp1_test3);
```

Why is it displaying the month number 9 (September) instead of 10 (October)? What is the correct way to achieve the 2022-10-01 format?

Thank you

**Comment by vresetnikov** [comment]
I have just spotted the `iso-month` setting, is this the answer? Why this separation? When are `month-pad` and `month-number` useful?

**Comment by spencermountain** [comment]
hey Vladimir - yep, this sucks. Javascript uses 0-based months, and 1-based days. it was a design decision we went with early on.
Your timing is good. I'm working on a breaking change, and may try to improve this
but yes, for now, 'iso-month' or a rogue +1 should do the trick
cheers

**Comment by vresetnikov** [comment]
> hey Vladimir - yep, this sucks. Javascript uses 0-based months, and 1-based days. it was a design decision we went with early on. Your timing is good. I'm working on a breaking change, and may try to improve this but yes, for now, 'iso-month' or a rogue +1 should do the trick cheers

Thank you very much for your continuous effort maintaining this awesome library
