### ISSUE TITLE
Feature Request - allow passing of arbitrary tzdata files.

### ISSUE THREAD

**Issue by ryami333** [spencermountain/spacetime#38]
There's this excellent family of IANA Timezone data files published on NPM now:

You can depend on _everything_ by using the root package:
https://www.npmjs.com/package/tzdata

Or, you can pull out just the areas that you want, like:
https://www.npmjs.com/package/tzdata-asia

It would be incredibly useful if `spacetime` were to expose an API for initialising with arbitrary tzdata so that we could manage both the accuracy and scope (and therefore bundle size) of our applications when using spacetime.

Nice wee package, enjoying it so far!

**Comment by spencermountain** [comment]
Hey! Mitch, I really like that idea. That makes a lot of sense. I think it would be useful and simple to do.
I'll try to look at it this week. 
Cheers

**Comment by spencermountain** [comment]
hey, I checked out that IANA package, but the zonefiles are missing a few pieces of data for our purposes.
The closest I got was this, which is now working in v3:
```js
const spacetime = require('spacetime')
const s = spacetime.today('UTC')
s.timezones = {
  'UTC/funZone': {
    o: 7, //+7 hours offset
    h: 'n', //hemisphere
    dst: '01/15:02->11/05:03' //when it enters daylight-savings-time
  }
}
s.goto('UTC/funZone')
s.debug()
// -  UTC/funZone (7)
```
it's kinda weird. Lemme know what you think.  Maybe we should publish `spacetime-asia`, `spacetime-europe` and things.
I'm gonna leave this open for now..

**Comment by ryami333** [comment]
Thanks for investigating - that won't suit my needs though I'm afraid. Take care!
