### ISSUE TITLE
Times of the day seem illogical

### ISSUE THREAD

**Issue by ChrisSeakane** [spencermountain/spacetime#385]
Was it intentional to define 'lunch' and 'noon' as being 12 hours apart?
And why is 'midnight' equal to 23:59pm ? This seems to be a mix of am/pm notation and 24hr clock... 

```
//some hard-coded times of day, like 'noon'
    dayTime: function (str, goFwd) {
      if (str !== undefined) {
        const times = {
          morning: '7:00am',
          breakfast: '7:00am',
          noon: '12:00am',
          lunch: '12:00pm',
          afternoon: '2:00pm',
          evening: '6:00pm',
          dinner: '6:00pm',
          night: '11:00pm',
          midnight: '23:59pm'
        };
```

**Comment by spencermountain** [comment]
yikes, ya that's pretty sloppy. Thank you for spotting this.

This method is planned to be removed in the next version - out of curiosity, what are you using it for?
Could be convinced to keep it. At minimum, users should be able to configure these. 

Happy to do a hotfix, if it's important for you.
cheers

**Comment by ChrisSeakane** [comment]
I don't need it - I was just browsing the code and it caught my eye.
No harm done if it's left out as far as I'm concerned.

**Comment by DarshanDixit05** [comment]
Hi 👋, If the bug is yet to be solved, can i work on it ?

**Comment by spencermountain** [comment]
sure!

**Comment by DarshanDixit05** [comment]
Hi @spencermountain, I wanted to test the "dayTime" function to check changes. Can you help me with it? Possibly a test case or something like that ?
The function that I'm talking about : 
<img width="827" alt="Screenshot 2023-05-09 032229" src="https://user-images.githubusercontent.com/76871537/236945683-f6f3d18e-2793-40ca-a179-9aba51abf9d4.png">

**Comment by spencermountain** [comment]
hey Darshan, the files in `./build` are compiled versions. You'll want to edit the files in `./src`
hope that helps
cheers

**Comment by Cyddharth-Gupta** [comment]
@spencermountain can you reassign the issue to me, there hasn't been any progress

**Comment by spencermountain** [comment]
hey @Cyddharth-Gupta apologies, i think this is fixed. I should have closed it.
These look right to me, but let me know if I'm wrong:

```js
import spacetime from './src/index.js'

let arr = [
  'morning',
  'breakfast',
  'noon',
  'lunch',
  'afternoon',
  'evening',
  'dinner',
  'night',
  'midnight',
]
arr.forEach(str => {
  let s = spacetime().dayTime(str)
  console.log(str, ' - ', s.format('iso-short'))
})
/*
morning  -  2023-07-10
breakfast  -  2023-07-10
noon  -  2023-07-10
lunch  -  2023-07-10
afternoon  -  2023-07-10
evening  -  2023-07-10
dinner  -  2023-07-10
night  -  2023-07-10
midnight  -  2023-07-10
*/
```
cheers

**Comment by Cyddharth-Gupta** [comment]
Hi @spencermountain thanks for confirming, seems correct to me as well.
Thanks
