### ISSUE TITLE
Epoch values not updating for different timezones

### ISSUE THREAD

**Issue by prenx4x** [spencermountain/spacetime#399]
I am trying to get epoch value for particular timezone.

```
const spacetimeNow = spacetime();
console.log(spacetimeNow);
console.log(spacetimeNow.goto("asia/dubai"));
console.log(spacetime.now("asia/dubai"));
```

Output:

```
SpaceTime {
  epoch: 1693330667371,
  tz: 'america/toronto',
  silent: true,
  british: undefined,
  _weekStart: 1,
  _today: {}
} 
SpaceTime {
  epoch: 1693330667371,
  tz: 'asia/dubai',
  silent: true,
  british: undefined,
  _weekStart: 1,
  _today: {}
}
SpaceTime {
  epoch: 1693330667371,
  tz: 'asia/dubai',
  silent: true,
  british: undefined,
  _weekStart: 1,
  _today: {}
}
```

As you can see the epoch is still the same. Isn't it supposed to be different for different timezone.
Is this a bug or I am doing something wrong?

Thanks.

**Comment by spencermountain** [comment]
hey Mufaddal - yep! epoch is like the universal heartbeat - same everywhere.
If you want to compare dates, you'll have to compare date-strings, like an ISO or something.
✌️ fellow torontonian
cheers

**Comment by spencermountain** [comment]
ps - hey hissab is cool!

**Comment by prenx4x** [comment]
@spencermountain Thanks for getting back so quickly.
So the actual issue is that I am trying to find difference in timezones using .diff function (or epoch).

I checked https://github.com/spencermountain/spacetime/issues/309 and will try to follow the code snippet you provided.

Are you planning to add timezone difference support in your .diff function anytime soon?
