### ISSUE TITLE
Typings file

### ISSUE THREAD

**Issue by spencermountain** [spencermountain/spacetime#4]
from recurrent googling, seems the popular way to expose the api now is a `.d.ts` typings file, and pointing to it from package.json. I'm easy regarding any alternative formats.

moment tests it [this way](https://github.com/moment/moment/tree/develop/typing-tests), which seems doable for us.
-thoughts @brianleroux ?

**Comment by ksnyde** [comment]
any update on this? open to a PR? Love the compact size of this library but everything I do is in TypeScript these days.

**Comment by ryanblock** [comment]
@ksnyde definitely open to a PR!

**Comment by spencermountain** [comment]
ah, been waiting for someone like you Ken! do it!
