### ISSUE TITLE
Africa/Cairo: wrong TZ offset

### ISSUE THREAD

**Issue by artask** [spencermountain/spacetime#404]
In Africa/Cairo parsed dates return wrong timezone offset. The offset is +1 while in fact it should be +2.

On the screenshot below: logged JS Date followed by spacetime(date).format('iso')
![image (1)](https://github.com/spencermountain/spacetime/assets/5480575/ed378686-d4fe-4c1b-ac3e-962621635aa5)

I see that in the previous patch release something similar has been fixed for Casablanca. I thought this may be related.

Thank you for the great package!

**Comment by spencermountain** [comment]
ah good catch! will add this to the next release.
ideally will be this week.
cheers

**Comment by spencermountain** [comment]
fixed in 7.5.0 - thank you!

**Comment by artask** [comment]
Amazing! Thanks for the quick fix!
