### ISSUE TITLE
DST seems to be incorrect for Europe/London

### ISSUE THREAD

**Issue by Stono** [spencermountain/spacetime#419]
Hey, i noticed that DST is wrong when going to `Europe/London`:

```
> spacetime('2024-10-31T09:00:00Z').goto('Europe/London').isDST()
false
> spacetime('2024-10-30T09:00:00Z').goto('Europe/London').isDST()
true
```

This should have adjusted on the 27th (last sunday in October), but instead appears to have taken the last day of the month instead.

**Comment by spencermountain** [comment]
hey Karl, i get `false, false` for this - can you ensure you're on the latest? 
thanks.

**Comment by Stono** [comment]
Welllll then, `spacetime` was in my `ncu` ignore list so wasn't getting updated and i was still on v6.
Sorry for wasting your time!
