### ISSUE TITLE
GreenLand (WST) shift their time from -3 to -2

### ISSUE THREAD

**Issue by flora9698** [spencermountain/spacetime#420]
Greenland's standard time will be UTC-2 from 25 March 2023, instead of UTC-3. Greenland will not switch to Daylight Saving Time this year, 2023, as the standard time for Greenland will change from UTC-3 to UTC-2. Greenland will change to Daylight Saving Time again in 2024 and onwards.

The announcement was made in 2022

**Comment by spencermountain** [comment]
thanks @flora9698 - I'll take a look this weekend.

**Comment by spencermountain** [comment]
thanks, I've changed the default offset for`america/nuuk`, and I think Thule and Danmarkshavn are still correct.
should be updated in `7.7.0`, please let me know if you see anything funny.
cheers
