### ISSUE TITLE
list timezones?

### ISSUE THREAD

**Issue by giladgray** [spencermountain/spacetime#43]
loving the lightweight timezone library, but i don't see a way to list all timezones.
you've got this whole data module, can we get a function to expose it? 

`spacetime.zones()` perhaps?

**Comment by spencermountain** [comment]
hey GIlad!
yeah, this is possible as-of last version, i just haven't documented it yet:
```js
const spacetime = require('spacetime')
const s = spacetime.today('UTC')
s.timezones
```
https://runkit.com/spencermountain/5a84425187b42500122cdf7a
is that gonna work?
cheers
