### ISSUE TITLE
Parse a new date in RFC822 format switches the offset (+/-)

### ISSUE THREAD

**Issue by vitormv** [spencermountain/spacetime#58]
When i parse a date with the offset speficied, trying to format the date as `iso` or `iso-utc` swaps the offset operator from `+` to `-` and vice versa.

Example:
http://jsfiddle.net/w082uros/6/

**Comment by spencermountain** [comment]
yikes!
thanks vitor, I'll take a look.

**Comment by spencermountain** [comment]
hey, fixed this in `4.3.0`

yeah, it's weird that '+ 7 hours' is represented at `-07:00` in that format.
who knew!

good find, thank you.

**Comment by vitormv** [comment]
That was fast! Thanks a lot!!
