### ISSUE TITLE
Possible to make timezone data tree-shakeable?

### ISSUE THREAD

**Issue by voxpelli** [spencermountain/spacetime#71]
My impression is that its the timezone data that makes up most of the size of a library like this.

As a follow up to #37: Would it perhaps be possible to make the timezone data tree-shakeable? So that only the data for the time zones that one are actively referencing gets included?

If you're unfamiliar with the concept, then here's some more reading: https://webpack.js.org/guides/tree-shaking/ It do require ESM

**Comment by spencermountain** [comment]
hey Pelle, yeah that's a cool idea.
I didn't know treeshaking could pluck keys out of an object. I suppose everything is possible. I like that idea.

**Comment by voxpelli** [comment]
It can treeshake the JSON itself: https://react-etc.net/entry/json-tree-shaking-lands-in-webpack-4-0

**Comment by spencermountain** [comment]
hey @voxpelli I've created an es-module version [here](https://github.com/spencermountain/spacetime/tree/esm-attempt/builds), using rollup.

I'm still not sure it's useful, can you take a look at it?

**Comment by voxpelli** [comment]
My understanding is that to enable tree-shaking one need to export each tree-shakeable thing individually – so while it’s good that it’s an es-module, it will always include everything I think because there’s only a single export.

By splitting things up in multiple exports something like webpack or rollup can pick just the exports that’s used and eliminate the rest – assuming that there are no side-effects of requiring the module and that the module has been indicated as having no side-effects so that webpack can know that

**Comment by spencermountain** [comment]
ah, thank you. that's helpful.

**Comment by spencermountain** [comment]
cleaning up issues, merging with #37 
thanks
