### ISSUE TITLE
Consider using git tags and Github releases

### ISSUE THREAD

**Issue by yvele** [spencermountain/spacetime#78]
Please consider using git tags when making releases. Specially useful with [Github release notifications](https://blog.github.com/changelog/2018-11-27-watch-releases/).

Also can you also consider ordering [changelolg](https://github.com/spencermountain/spacetime/blob/master/changelog.md)  from the most recent release to the older.

Thanks.

**Comment by spencermountain** [comment]
hey, yeah you're right about this.
here's [5.0.4](https://github.com/spencermountain/spacetime/releases/tag/5.0.4)
cheers
