### ISSUE TITLE
spacetime is not defined

### ISSUE THREAD

**Issue by tapiamcclung** [spencermountain/spacetime#79]
Hi,
After a couple of weeks of pausing, I just pulled a project I was working on that uses spacetime.
However, I keep getting "spacetime is not defined" regardless of using 
`<script src="https://unpkg.com/spacetime"></script>`, 
`https://unpkg.com/spacetime@5.0.4/builds/spacetime.min.js`
or  if `src` is a local file copied from that same URL
Any pointers? :/
Thanks a lot!

**Comment by spencermountain** [comment]
thanks @tapiamcclung i was worried about this. I played-around with the build process last release.
let me check it out.

**Comment by spencermountain** [comment]
yikes, `https://unpkg.com/spacetime@5.0.6/builds/spacetime.min.js` works, but the bare url still has a weird redirect. maybe there's a lag. will keep this open
thanks for the heads-up.

**Comment by spencermountain** [comment]
works now!
https://twitter.com/unpkg/status/1075581138649792513

thanks
