### ISSUE TITLE
"since" seems output unexpected differences

### ISSUE THREAD

**Issue by hunteva** [spencermountain/spacetime#89]
Not sure this is a bug or misunderstand the API.
"since" call seems to output some questionable result, please refer the screenshots below.

![image](https://user-images.githubusercontent.com/491380/52091175-6e1d5f00-2618-11e9-8597-d3f122f62068.png)

couldn't understand why it's '3 days 11 hours ago', since 'diff' with days only output -1

**Comment by spencermountain** [comment]
whoa, that does look wrong.
I'll check it out.

**Comment by hunteva** [comment]
I guess "who smells it who deals it", so here is the [PR](https://github.com/spencermountain/spacetime/pull/91) to fix it, please let me know your thoughts.

Cheers
