### ISSUE TITLE
'diff-big' test fail on specific time

### ISSUE THREAD

**Issue by hunteva** [spencermountain/spacetime#92]
Pretty sure it's related to #90  feel need to document it here since it breaks tests.

![image](https://user-images.githubusercontent.com/491380/52176290-b2c21980-2815-11e9-8e48-3ed30376d488.png)

As can seen from above, there was 20 days difference when running it later. (10 days diff if only minus 10 year)

Glad to fix on this one by the way.

**Comment by spencermountain** [comment]
hey, just tidying up -  this seems to be working now:
```js
let a = spacetime('July 27 2018')
let b = a.clone().minus(20, 'years')
console.log(b.diff(a).days)
//7305

let a2 = spacetime('July 27 2018', 'Pacific/Auckland')
let b2 = a.clone().minus(20, 'years')
console.log(b2.diff(a2).days)
//7305
```
lemme know if i'm missing the issue
cheers
