### ISSUE TITLE
Possible a timezone issue, .d property wrong value

### ISSUE THREAD

**Issue by valentinradu** [spencermountain/spacetime#97]
Give the following snipet:
```
const spacetime = require('spacetime')
const date = spacetime('2019-02-16T23:14:34+01:00')
// date.d -> 2019-02-16T21:14:34.157Z !incorrect
// date.iso() -> 2019-02-16T23:14:34.157+01:00 correct
const otherDate = new Date(Date.parse(date.iso()))
// otherDate -> 2019-02-16T22:14:34.157Z correct
```

It seems that the `.d` property has some issues with (probably) the timezone? In any case, it's not a representation of the parsed date.

**Comment by spencermountain** [comment]
hey @valentinradu the `.d` property is only meant to be used internally, it doesn't have the offset applied. maybe it should have been called `._d` or something.
maybe we should have a method that wraps ` new Date(Date.parse(date.iso()))`, like you have cleverly found.

**Comment by valentinradu** [comment]
@spencermountain Ah, ok, thanks for the clarification! The `.d` property was documented in the docs so I assumed it's open for the public.

**Comment by spencermountain** [comment]
removed this from the docs. thanks for the heads-up!
