### ISSUE TITLE
Error when trying to change time zone to Tomsk, Volgograd and +13

### ISSUE THREAD

**Issue by talkor** [spencermountain/spacetime#98]
When trying to change time zone to:

- Asia/Tomsk
- Asia/Volgograd 
- Coordinated Universal time +13 

using `.goto()` it returns an error: Cannot read property 'dst' of undefined.

In the pictures below trying to load spacetime.how website after changing the computer's time zone to these 3 time zones and getting that error. Checked with all time zones provided with Windows 10 settings and only those three returned this error.

![timezone-universal-plus13](https://user-images.githubusercontent.com/18269880/52996951-be255f80-3427-11e9-84fc-6c63db76a747.png)
![timezone-volgo](https://user-images.githubusercontent.com/18269880/52996952-be255f80-3427-11e9-84fc-0e576d9c7e43.png)
![tomsk-error 1](https://user-images.githubusercontent.com/18269880/52996953-be255f80-3427-11e9-98b5-2d71aba7701e.png)

**Comment by spencermountain** [comment]
thank you! happy to fix this

**Comment by spencermountain** [comment]
added them in `5.3.0`
thanks!

**Comment by talkor** [comment]
Awesome! Thank you!
