### ISSUE TITLE
zero-pad timezone offset

### ISSUE THREAD

**Issue by nicobytes** [spencermountain/spacetime#99]
I have a question I was using the unix format "yyyy-MM-ddTHH:mm:ssZ"

`date.unixFmt('yyyy-MM-ddTHH:mm:ssZ');`

![screen shot 2019-02-20 at 11 29 29 am](https://user-images.githubusercontent.com/7611944/53107338-d8803b80-3502-11e9-9437-91ea128e444b.png)

But it is wrong because the timezone format should have ZeroPad.

![screen shot 2019-02-20 at 11 30 53 am](https://user-images.githubusercontent.com/7611944/53107437-049bbc80-3503-11e9-8ad1-227fdcb2629d.png)

I think it would still print:

`2019-02-20T12:29:10-0400` and `2019-02-20T11:29:20-0500`

![screen shot 2019-02-20 at 11 40 43 am](https://user-images.githubusercontent.com/7611944/53108092-690b4b80-3504-11e9-90ee-2f33df4775b2.png)

**Comment by spencermountain** [comment]
👍
